---
title: "analysis_ObjectFamRatings_v2"
author: "Bria Long"
date: "10/17/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Include libraries

```{r}
suppressPackageStartupMessages(c("dplyr","langcog","tidyr","ggplot2","lme4"))
library(dplyr)
library(ggplot2)
library(rjson)
library(stringr)
library(tidyr)
library(dplyr)
library(forcats)

```

## load datafiles and put in a data frame
```{r}
files <- dir("../production-results/")

d.raw <- data.frame()

for (f in files) {
  jf <- paste("../production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- data.frame(workerid = jd$WorkerId, 
                   rating = as.numeric(jd$answers$data$rating),
                   childsAge = jd$answers$data$childsAge,
                   imageName = jd$answers$data$imageName)
  d.raw <- bind_rows(d.raw, id)
}

# function for shorter filename extraction
shortFileName <- function(fileName){
  out=strsplit(as.character(fileName),"/")[[1]][8]
}

# make shorter iamge names for plots, etc.
d.raw <- d.raw %>%
  group_by(imageName) %>%
  mutate(imageNameShort = shortFileName(imageName))
```

2. Do some basic preprocessing - get rid of parents who have kids the wrong age
```{r d.pretty}
# pre-process: get children's age and filter by too young/old
d.pretty <- d.raw %>%
  group_by(childsAge) %>%
  mutate(ageShort = as.numeric(substr(childsAge,1,2))) %>%
  filter(ageShort > 9)  %>%
  group_by(imageNameShort) %>%
  multi_boot_standard(col = "rating")  %>%
  ungroup  %>%
  mutate(imageNameShort = fct_reorder(imageNameShort, mean))


# toInclude=c('stapler.jpg','holepunch.jpg','walkman.jpg','bikebell.jpg')
# d.subset <- d.pretty %>%
#   group_by(workerid, imageNameShort) %>%
#   filter(is.element(imageNameShort,toInclude))
```

3. Quick plot


```{r d.prety, echo=FALSE}
# show plots for each object

ggplot(d.pretty, aes(x = factor(imageNameShort), y = mean, col = imageNameShort)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) +
   theme(axis.text.x = element_text(angle = 90, hjust = 1))


  


# 
```

