---
title: "analysis_ObjectFamRatings_v4_multiQ"
author: "Bria Long"
date: "3/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Include libraries

```{r}
suppressPackageStartupMessages(c("dplyr","langcog","tidyr","ggplot2","lme4"))
library(imager)
library(langcog)
library(ggplot2)
library(rjson)
library(stringr)
library(tidyr)
library(forcats)
library(tidyverse)
library(here)
```

## load datafiles and put in a data frame
```{r}
files <- dir("../production-results/")
d.raw <- data.frame()

for (f in files) {
  jf <- paste("../production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- data.frame(workerid = jd$WorkerId, 
                   seenObject = as.numeric(jd$answers$data$seenObject)[1:85],
                   knowFunction = as.numeric(jd$answers$data$knowFunction)[1:85],
                   knowLabel = as.numeric(jd$answers$data$knowObjectLabel)[1:85],
                   childsAge = jd$answers$data$childsAge,
                   imageName = jd$answers$data$imageName)
  d.raw <- bind_rows(d.raw, id)
}

# function for shorter filename extraction
shortFileName <- function(fileName){
  out=strsplit(as.character(fileName),"/")[[1]][8]
}

# make shorter iamge names for plots, etc.
d.raw <- d.raw %>%
  group_by(imageName) %>%
  dplyr::mutate(imageNameShort = shortFileName(imageName))
```

2. Do some basic preprocessing - filter by unfamiliar objects
```{r d.pretty}
# pre-process: get children's age and filter by too young/old

thres=.25

d.unfamiliar <- d.raw %>%
  group_by(imageNameShort) %>%
  dplyr::summarize(avgSeenObject = mean(seenObject), avgKnowLabel = mean(knowLabel), avgKnowFunction = mean(knowFunction)) %>%
  dplyr::mutate(imageNameShort = fct_reorder(imageNameShort, avgSeenObject)) %>% ## reorders varibles accordinf to #avgSeenObject for plotting
  dplyr::mutate(unFamiliar = (avgSeenObject<= thres & avgKnowLabel<=thres  & avgKnowFunction<=thres)) %>%
  filter(unFamiliar == TRUE) ## only get unfamiliar objects

```

3. Quick plot
```{r}
ggplot(d.unfamiliar, aes(x = as.factor(imageNameShort), y = avgSeenObject)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

4. Automated selection of objects and output csv with those categories
```{r}
write.csv(d.unfamiliar,"UnfamiliarObjects_ForNorming.csv")
```

5. Write out these images to a directory
```{r}
imgPath= 'stimuliGeneration/famRatings/experiment/imagesToNorm/' # get images from here
imgPathSave= 'stimuliGeneration/famRatings/analysis/selectedImages/' # save here

# go through and save full paths for each images
saveImages <- d.unfamiliar %>%
  mutate(fileName = paste0(here::here(imgPath),imageNameShort)) %>%
  mutate(saveFileName = paste0(here::here(imgPathSave),imageNameShort))

# turn special characters back into spaces
saveImages$saveFileName = gsub("%20", " ", saveImages$saveFileName)
saveImages$fileName = gsub("%20", " ", saveImages$fileName)

# save out each images to this new direcotry
for (imageInd in 1:length(saveImages$fileName)) {
  thisImageName = saveImages$fileName[imageInd]
  thisImage=load.image(thisImageName)
  thisSaveImName = saveImages$saveFileName[imageInd]
  imager::save.image(thisImage,thisSaveImName)
}

```


